config/routes.rb
Rails.application.routes.draw do
  resources :userwebs
  get 'CART' =>'userwebs#addcart'
  get 'cartshow' =>'userwebs#cart'
  get 'profile' =>'userwebs#profile'
  get 'form'=>'userwebs#form'
  post 'profilecreate' =>'userwebs#profilecreate'
  get 'delete' =>'userwebs#delete'
  post 'edit_cart' =>'userwebs#edit_cart'
  get 'editcartpage' =>'userwebs#editcartpage'
  get 'deleteproduct' =>'e_markets#deleteproduct'

  get 'shoe' => 'userwebs#shoe'

  get 'glossary' => 'userwebs#Glossary'
  get 'mobiles' => 'userwebs#Mobiles'
  get 'dress' => 'userwebs#dress'
  devise_for :users
  resources :e_markets
 

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/e_market.rb
class EMarket < ActiveRecord::Base
	mount_uploader :image, ProductUploader
end

app/controllers/e_markets_controller.rb
class EMarketsController < ApplicationController
  before_action :set_e_market, only: [:show, :edit, :update, :destroy]

  # GET /e_markets
  # GET /e_markets.json
  def index
    @e_markets = EMarket.all
  end

  # GET /e_markets/1
  # GET /e_markets/1.json
  def show
  end

  # GET /e_markets/new
  def new
    @e_market = EMarket.new
  end

  # GET /e_markets/1/edit
  def edit
  end
  def deleteproduct
    id = params[:id]
    data = EMarket.where(id: id).first
    data.destroy
    redirect_to '/'
  end


  # POST /e_markets
  # POST /e_markets.json
  def create
    @e_market = EMarket.new(e_market_params)

    respond_to do |format|
      if @e_market.save
        format.html { redirect_to @e_market, notice: 'E market was successfully created.' }
        format.json { render :show, status: :created, location: @e_market }
      else
        format.html { render :new }
        format.json { render json: @e_market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /e_markets/1
  # PATCH/PUT /e_markets/1.json
  def update
    respond_to do |format|
      if @e_market.update(e_market_params)
        format.html { redirect_to @e_market, notice: 'E market was successfully updated.' }
        format.json { render :show, status: :ok, location: @e_market }
      else
        format.html { render :edit }
        format.json { render json: @e_market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /e_markets/1
  # DELETE /e_markets/1.json
  def destroy
    @e_market.destroy
    respond_to do |format|
      format.html { redirect_to e_markets_url, notice: 'E market was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_e_market
      @e_market = EMarket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def e_market_params
      params.require(:e_market).permit(:protect_name, :protect_id, :specification, :price,:image,:category)
    end
end

app/helpers/e_markets_helper.rb
module EMarketsHelper
end

app/views/e_markets/_form.html.erb
<%= form_for(@e_market) do |f| %>
  <% if @e_market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@e_market.errors.count, "error") %> prohibited this e_market from being saved:</h2>

      <ul>
      <% @e_market.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field",class="form-group">
    <%= f.label :protect_name %><br>
    <%= f.text_field :protect_name, class:"form-control", style:"width: 40%;"%>
  </div>
  <div class="field">
    <%= f.label :protect_id %><br>
    <%= f.text_field :protect_id , class:"form-control", style:"width: 40%;"%>
  </div>
  <div class="field">
    <%= f.label :specification %><br>
    <%= f.text_field :specification , class:"form-control", style:"width: 40%;"%>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(["mobiles", "glossary", "dress","shoe"]), {}, class: "form-control", style: "width: 40%;" %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price ,class:"form-control", style:"width: 20%;" %>
  </div>
  <div class="field" >
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "my-submit-button"  %>
  </div>
<% end %>

app/views/e_markets/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">E-markets</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if user_signed_in?%>
          <% if current_user.role != "admin" %>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="mobiles">Mobiles</a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="dress">Dress</a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="glossary">Glossary</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="shoe">shoe</a>
            </li>
          <%end%>  
          <li class="nav-item">
            <div class="nav-link" >
              <%= link_to "Edit account", edit_user_registration_path ,style:"color:white;" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link" >
              <%= link_to "Sign_out", destroy_user_session_path ,style:"color:red;"%>
            </div>
          </li>
        <%end%>

        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>

    </div>
    
    <div style="margin-right:3%">
      <a href="profile"  class="my-link">profile</a>
    </div>

  </div>
</nav>

<style>
  .my-link {
    color: white;
    text-decoration: none;
    hover:none;
  }
</style>

app/views/e_markets/edit.html.erb
<h1>Editing e_market</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @e_market, class: "btn btn-success" %> |
<%= link_to 'Back', e_markets_path, class: "btn btn-primary" %>

app/views/e_markets/index.html.erb
<style>
  .products {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
  }
  
  .product {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  .product img {
    max-width: 100%;
    height: auto;
  }
</style>
<% if user_signed_in?%>
<h1>Product of e-markets</h1>
<br>
<%= link_to "Create product", new_e_market_path, method: :post , class: "btn btn-primary" %>
<br><br>
<div class="products">
  <% @e_markets.each do |e_market| %>
    <div class="product">
      <%= link_to(image_tag(e_market.image), e_market) %>
      <br><br>
      <ul style="display:flex;">
        <ol style="margin-left:0%;" >
          <h5><%= link_to 'Edit', edit_e_market_path(e_market), class: "btn btn-primary" %></h5>
        </ol>
        <ol>
          <h5><%= link_to 'show', e_market, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
        </ol>
        <ol>
          <h5><%= link_to "Delete", deleteproduct_path(action: "addcart",id: e_market.id), method: :get, class: "btn btn-danger" %></h5>
        </ol>
      </ul>
      
    </div>
  <% end %>
</div>
<br>
<%else%>
  <%= link_to "Sign_up", new_user_registration_path %><br>
  <%= link_to "Log_in", new_user_session_path %><br>
<%end%>

app/views/e_markets/new.html.erb
<h1>New e_market</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', e_markets_path , class: "btn btn-primary"%>

app/views/e_markets/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Protect name:</th>
      <th>Protect:</th>
      <th>Specification:</th>
      <th>Price:</th>      
    </tr>
  </thead>  
  <tbody>
    <tr>
      <td><%= @e_market.protect_name %></td>
      <td> <%= @e_market.protect_id %></td>
      <td><%= @e_market.specification %></td>  
      <td>$<%= @e_market.price %></td> 
    <tr>
  </tbody>
</table>
<h2>IMAGE:</h2>
<%= image_tag @e_market.image,width:"250px" %>
<div>

  <% if current_user.role == 'admin' %>
    <%= link_to 'Edit', edit_e_market_path(@e_market), class: "btn btn-success" %> |
    <%= link_to 'Back', e_markets_path, class: "btn btn-primary" %>
  <%end%>
</div>
<br>
<br>
<br>