config/routes.rb
Rails.application.routes.draw do
  resources :userwebs
  get 'CART' =>'userwebs#addcart'
  get 'cartshow' =>'userwebs#cart'
  get 'profile' =>'userwebs#profile'
  get 'form'=>'userwebs#form'
  post 'profilecreate' =>'userwebs#profilecreate'
  get 'delete' =>'userwebs#delete'
  post 'edit_cart' =>'userwebs#edit_cart'
  get 'editcartpage' =>'userwebs#editcartpage'
  get 'deleteproduct' =>'e_markets#deleteproduct'

  get 'shoe' => 'userwebs#shoe'

  get 'glossary' => 'userwebs#Glossary'
  get 'mobiles' => 'userwebs#Mobiles'
  get 'dress' => 'userwebs#dress'
  devise_for :users
  resources :e_markets
 

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/userweb.rb
class Userweb < ActiveRecord::Base
	
end

app/controllers/userwebs_controller.rb
class UserwebsController < ApplicationController
  before_action :set_userweb, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @e_markets = EMarket.all
    
    @userwebs = Userweb.all
    respond_with(@userwebs)
  end

  def show
    @e_markets = EMarket.all

    respond_with(@userweb)
  end

  def new
    @userweb = Userweb.new
    respond_with(@userweb)
  end

  def edit


  end


  def addcart
    product_id = params[:id]
    names = params[:Protect_name]
    product = params[:Protect]
    specification = params[:Specification]
    price = params[:Price]
    image = params[:image]
    
    das6 = Cart.where(user_id: current_user.id,product_id:product_id).first
    p das6.present?.to_s
    if das6.present?
      puts das6.quentity.class.inspect+"ggggggggggggggggggggggggggg"
      brr = das6.quentity.to_i+1
      das6.update_attribute(:quentity, brr.to_s)
       var  = das6.total_cost.to_i+price.to_i
      das6.update_attribute(:total_cost, var )     
    else
      saveCart = Cart.create(user_id: current_user.id,quentity: "1",product_id: product_id,product_names:names,product:product,specification:specification,real_price:price,image: image,total_cost: price)
    end
    redirect_to request.referrer
  end

  def cart
    obj = []
    user = current_user.id
    puts  user.inspect+"hhhhhhhhhhhhhhhhhhhhhhh"
    datae = Cart.where(user_id: user)
    if datae.present?
      datae.each do |s|
        datas = Cart.where(user_id: user,product_id: s.product_id).first
        obj.push(datas)
      end
      @e_mars = obj
       puts  @e_mars.inspect+"hhhhhhhhhhhhhhhhhhhhhhhhh"
    else
      @e_mars = ''
    end
  end

  def delete
    user = current_user.id
    product_id = params[:product_id]
    data = Cart.where(user_id: user,product_id: product_id).first
    data.destroy
    redirect_to request.referrer
    #redirect_to 'userwebs/cart'
  end

  def editcartpage
    @name = params[:product_names]
    @quantity =params[:quantity]
    @image = params[:image]
    @product_id = params[:product_id]

  end



  def shoe
    dress = EMarket.where(category: "shoe")
    @e_markets = dress

  end

  def edit_cart
    
    quantity = params[:edit_cart_path]["quantity"]

    product_id = params[:edit_cart_path]["product_id"]


    data = Cart.where(user_id: current_user.id, product_id: product_id).first
    puts quantity.inspect+"hhhhhhhhhhhhhiiiojukgfudfj"
    total = data.real_price.to_i * quantity.to_i
    puts total.inspect+"hhhhhhhhhhhhhiiiojukgfudfj"
    data.update_attribute(:quentity, quantity )
    data.update_attribute(:total_cost, total)
    redirect_to '/'

  end


  def Glossary
    dress = EMarket.where(category: "glossary")
    @e_markets = dress

  end

  def dress
    dress = EMarket.where(category: "dress")
    @e_markets = dress

  end
  
  def Mobiles
    dress = EMarket.where(category: "mobiles")
    @e_markets = dress

  end


  def profile
    @user = User.where(id: current_user.id).first
    @userse = @user.email.to_s
    @username = @user.user_name.to_s
  end



  def profilecreate
    names = params[:profilecreate_path]["cart"]
    image = params[:profilecreate_path]["avatar"].filename
    puts image.inspect+"jjjjjjjjj326435875696790878-07jjjjwgdweg"
    username = User.where(id: current_user.id).first
    username.update_attribute(:user_name, names)
    username.update_attribute(:image, image)

    



    redirect_to '/'
  end




  def form

    puts "jjjjjjjjjjjjjwgdweg"

  end

  def create
    @userweb = Userweb.new(userweb_params)
    @userweb.save
    respond_with(@userweb)
  end

  def update
    @userweb.update(userweb_params)
    respond_with(@userweb)
  end

  def destroy
    @userweb.destroy
    respond_with(@userweb)
  end

  private
    def set_userweb
      @userweb = Userweb.find(params[:id])
    end

    def userweb_params
      params.require(:userweb).permit(:cart, :user_id, :quantity)
    end
end

app/helpers/userwebs_helper.rb
module UserwebsHelper
end

app/views/userwebs/Glossary.html.erb
<style>
  .products {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
  }
  
  .product {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  .product img {
    max-width: 100%;
    height: auto;
  }
</style>

<h1>Product of e-markets</h1>
<h5><%= link_to 'My Cart', cartshow_path(action: "mycart"), method: :post, class: "btn btn-primary" %></h5>
<br>
<%=link_to (image_tag("d8.png", width: 1100, height: 200)),dress_path%>
<br>
<br>
<div class="products">
  <% @e_markets.each do |e_market| %>
    <div class="product">
      <%= link_to(image_tag(e_market.image), e_market) %>
      <br>
      <br>
      <h5><%= link_to 'Show detail', e_market, class: "btn btn-success" %></h5>
      <% if current_user.role != "admin"%>
        <h5><%= link_to 'Add Cart', CART_path(action: "addcart", id: e_market.id, Protect_name: e_market.protect_name, Protect: e_market.protect_id, Specification: e_market.specification, Price: e_market.price, image: e_market.image), method: :post, class: "btn btn-primary" %></h5>
      <%end%>
    </div>
  <% end %>
</div>
<br>
<%=link_to (image_tag("ad.png", width: 1100, height: 250)),mobiles_path%>

app/views/userwebs/Mobiles.html.erb
<style>
  .products {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
  }
  
  .product {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  .product img {
    max-width: 100%;
    height: auto;
  }
</style>

<h1>Product of e-markets</h1>
<h5><%= link_to 'My Cart', cartshow_path(action: "mycart"), method: :post, class: "btn btn-primary" %></h5>
<%=link_to (image_tag("d8.png", width: 1100, height: 200)),dress_path%>
<br>
<br>
<div class="products">
  <% @e_markets.each do |e_market| %>
    <div class="product">
      <%= link_to(image_tag(e_market.image), e_market) %>
      <br>
      <br>
      <h5><%= link_to 'Show detail', e_market, class: "btn btn-success" %></h5>
      <% if current_user.role != "admin"%>
        <h5><%= link_to 'Add Cart', CART_path(action: "addcart", id: e_market.id, Protect_name: e_market.protect_name, Protect: e_market.protect_id, Specification: e_market.specification, Price: e_market.price, image: e_market.image), method: :post, class: "btn btn-primary" %></h5>
      <%end%>
    </div>
  <% end %>
</div>
<br>

app/views/userwebs/cart.html.erb
<h1>Cart</h1>
<% if @e_mars != ''%>
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th>Product name:</th>
        <th>Product_details:</th>
        <th>Specification:</th>
        <th>quantity:</th> 
        <th>total cost:</th> 
        
        <th>edit</th>
        <th>Delete</th>
        <th>Product</th>
      </tr>

    </thead>

    <tbody>
      <% @e_mars.each do |e_mars| %>
        <tr>
  	      <td><%= e_mars.product_names %></td>
  	      <td> <%= e_mars.product %></td>
  	      <td><%= e_mars.specification %></td>
          <td><%= e_mars.quentity %></td>   
  	      <td>$<%= e_mars.total_cost %></td> 

          <td style="padding-left: 10px;"><%= link_to "edit", editcartpage_path(action: "edit_cart", id: current_user.id,product_id: e_mars.product_id,product_names:e_mars.product_names,quantity:e_mars.quentity,image:e_mars.image), method: :get, class: "btn btn-info" %></td>


          <td style="padding-left: 10px;"><%= link_to "delete", delete_path(action: "delete", id: current_user.id,product_id: e_mars.product_id), method: :get, class: "btn btn-danger" %></td>


  	      <td><%= image_tag e_mars.image,width:"40px" %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
<%else%>
  <div class="border" style="text-align: center;margin-top: 3%;">
    <h5 style="color: red; margin-top: auto;">nothing to add to cart</h5>
  </div>
  
<%end%>

<br>

app/views/userwebs/dress.html.erb
<style>
  .products {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
  }
  
  .product {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  .product img {
    max-width: 100%;
    height: auto;
  }
</style>

<h1>Product of e-markets</h1>
<h5><%= link_to 'My Cart', cartshow_path(action: "mycart"), method: :post, class: "btn btn-primary" %></h5>

<br>
<br>
<div class="products">
  <% @e_markets.each do |e_market| %>
    <div class="product">
      <%= link_to(image_tag(e_market.image), e_market) %>
      <br>
      <br>
      <h5><%= link_to 'Show detail', e_market, class: "btn btn-success" %></h5>
      <% if current_user.role != "admin"%>
        <h5><%= link_to 'Add Cart', CART_path(action: "addcart", id: e_market.id, Protect_name: e_market.protect_name, Protect: e_market.protect_id, Specification: e_market.specification, Price: e_market.price, image: e_market.image), method: :post, class: "btn btn-primary" %></h5>
      <%end%>
    </div>
  <% end %>
</div>
<br>
<%= image_tag("adds.png", width: 1100, height: 200) %>

app/views/userwebs/edit.html.erb
<h1>Editing userweb</h1>

<%= render 'form' %>

<%= link_to 'Show', @userweb %> |
<%= link_to 'Back', userwebs_path %>

app/views/userwebs/editcartpage.html.erb
<div style="display: flex;">
  <div style="width: 60%;">
    <%= form_for :edit_cart_path, url: edit_cart_path do |f| %>
      <h3 >Edit Quantity E-market</h3>
      <br>
      <div class="field">
        <h4>Name</h4>
        <%= f.text_field :name, value: @name ,class:"form-control", style:"width: 70%;"%>
      </div>
        <div class="field">
        <h4>quantity</h4>
        <%= f.text_field :quantity, value: @quantity,class:"form-control", style:"width: 70%;" %>
      </div>

      <div class="field">
        <h4>product_id</h4>
        <%= f.text_field :product_id, value: @product_id ,class:"form-control", style:"width: 70%;"%>
      </div>
      <br>
      <div class="actions">
        <%= f.submit class: "my-submit-button" %>
      </div>
    <% end %>
  </div>
  <br>
  <div style="margin-left: 0%;width: 40%;">
    <%= image_tag(@image, style: "width:200px;margin-top:0px;") %>
  </div>
</div>

app/views/userwebs/form.html.erb
<h2>Edit Profile</h2>
<br>
<%= form_for :profilecreate_path, url: profilecreate_path do |f| %>
  <div class="field">
    <h4>User name</h4>
    <%= f.text_field :cart ,class:"form-control", style:"width: 20%;"%>
  </div>
  <br>
  <div class="field">
    <h4>Profile Image</h4>
    <%= f.file_field :avatar %>
  </div>
  <br>
  <div class="actions">

    <%= f.submit class: "my-submit-button"  %>
  </div>
<% end %>

app/views/userwebs/index.html.erb
<style>
  .products {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
  }
  
  .product {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  .product img {
    max-width: 100%;
    height: auto;
  }
</style>

<h1>Product of e-markets</h1>
<h5><%= link_to 'My Cart', cartshow_path(action: "mycart"), method: :post, class: "btn btn-primary" %></h5>
<%=link_to (image_tag("ad.png", width: 1100, height: 200)),mobiles_path%>
<br>
<br>

<div class="products">
  <% @e_markets.each do |e_market| %>

    <div class="product">
      <%= link_to(image_tag(e_market.image), e_market) %>
      <br>
      <h5><%= link_to 'Show detail', e_market, class: "btn btn-success" %></h5>
      <h5><%= link_to 'Add Cart', CART_path(action: "addcart", id: e_market.id, Protect_name: e_market.protect_name, Protect: e_market.protect_id, Specification: e_market.specification, Price: e_market.price, image: e_market.image), method: :post, class: "btn btn-primary" %></h5>
    </div>
  <% end %>
</div>
<br>
<%= image_tag("adds.png", width: 1100, height: 200) %>

app/views/userwebs/new.html.erb
<h1>New userweb</h1>

<%= render 'form' %>

<%= link_to 'Back', userwebs_path %>

app/views/userwebs/profile.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-4">

        <div class="card" style="border-radius: 15px;">
          <div class="card-body text-center">
            <div class="mt-3 mb-4">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                class="rounded-circle img-fluid" style="width: 100px;" />
            </div>
            <h4 class="mb-2"><%= @username %></h4>   
            <p class="text-muted mb-4">E-market <span class="mx-2">|</span> <%= @user.email %></p>
            <div class="mb-4 pb-2">
              <button type="button" class="btn btn-outline-primary btn-floating">
                <i class="fab fa-facebook-f fa-lg"></i>
              </button>
              <button type="button" class="btn btn-outline-primary btn-floating">
                <i class="fab fa-twitter fa-lg"></i>
              </button>
              <button type="button" class="btn btn-outline-primary btn-floating">
                <i class="fab fa-skype fa-lg"></i>
              </button>
            </div>
            <button type="button" class="btn btn-primary btn-rounded btn-lg">
              <a href="form"  class="my-link">EDIT PROFILE</a>
            </button>
            <br><br>
            <button type="button" class="btn btn-primary btn-rounded btn-lg">
              <a href="/"  class="my-link">Back</a>
            </button>
            <div class="d-flex justify-content-center text-center mt-5 mb-2">

<!--               <div class="px-3">
                <p class="mb-2 h5">8512</p>
                <p class="text-muted mb-0">Income amounts</p>
              </div> -->
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/userwebs/shoe.html.erb
<h1>shoe</h1>
<style>
  .products {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
  }
  
  .product {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  .product img {
    max-width: 100%;
    height: auto;
  }
</style>

<h1>Product of e-markets</h1>
<h5><%= link_to 'My Cart', cartshow_path(action: "mycart"), method: :post, class: "btn btn-primary" %></h5>
<br>

<br>
<br>
<div class="products">
  <% @e_markets.each do |e_market| %>
    <div class="product">
      <%= link_to(image_tag(e_market.image), e_market) %>
      <br>
      <br>
      <h5><%= link_to 'Show detail', e_market, class: "btn btn-success" %></h5>
      <% if current_user.role != "admin"%>
        <h5><%= link_to 'Add Cart', CART_path(action: "addcart", id: e_market.id, Protect_name: e_market.protect_name, Protect: e_market.protect_id, Specification: e_market.specification, Price: e_market.price, image: e_market.image), method: :post, class: "btn btn-primary" %></h5>
      <%end%>
    </div>
  <% end %>
</div>
<br>
<%=link_to (image_tag("ad.png", width: 1100, height: 250)),mobiles_path%>

app/views/userwebs/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Protect name:</th>
      <th>Protect:</th>
      <th>Specification:</th>
      <th>Price:</th>      
    </tr>
  </thead>  
  <tbody>
    <tr>
      <td><%= @e_market.protect_name %></td>
      <td> <%= @e_market.protect_id %></td>
      <td><%= @e_market.specification %></td>  
      <td><%= @e_market.price %></td> 
    <tr>
  </tbody>
</table>
<h2>IMAGE:</h2>
<%= image_tag @e_market.image,width:"250px" %>
<div>
  <%= link_to 'Edit', edit_e_market_path(@e_market) , class: "btn btn-success"%> |
  <%= link_to 'Back', e_markets_path , class: "btn btn-primary"%>
</div>